# Introducción a PyTorch, una biblioteca de aprendizaje profundo

Vehículos autónomos, smartphones, motores de búsqueda... El aprendizaje profundo está ahora en todas partes. Antes de empezar a crear modelos complejos, te familizarizarás con PyTorch, un marco de aprendizaje profundo. Aprenderás a manipular tensores, crear estructuras de datos de PyTorch y construir tu primera red neuronal en PyTorch con capas lineales.

## Introducción al aprendizaje profundo con PyTorch

- ¡El aprendizaje profundo está en todas partes

    - Traducción de idiomas
    - Vehículos autónomos
    - Diagnósticos médicos.
    - Chatbots


- ¿Qué es el aprendizaje profundo?

    - Es un subconjunto del aprendizaje automático
    - La estructura fundamental del modelo es una red de entradas, capas ocultas y salidas.
    - La red puede tener una o muchas capas ocultas.


- Redes de aprendizaje profundo

    - Inspirado en cómo aprende el cerebro humano.
    - Neuronas -> Redes Neuronales
    - Los modelos requieren una gran cantidad de datos


- PyTorch: un framework de aprendizaje profundo

    - Uno de los frameworks más populares.
    - Originalmente desarrollado por Meta AI, ahora parte de Linux Foundation.
    - Intuitivo y fácil de usar
    - Similar a Numpy


- Tensores PyTorch

    - Tensor:
        - Similar a un arreglo o matriz
        - Bloques de construcción de las redes neuronales

Se puede importar la librería con el comando `import torch`
```{python}
import torch
my_list = [[1, 2, 3], [4, 5, 6]]
tensor = torch.tensor(my_list)
print(tensor)
```

- Atributos del tensor

    - Forma del tensor

```{python}
my_list = [[1, 2, 3], [4, 5, 6]]
tensor = torch.tensor(my_list)
print(tensor.shape)
```

    - Tipo de datos del tensor

```{python}
print(tensor.dtype)
```

### Introducción a las operaciones con tensores

**Formas compatibles**

```{python}
a = torch.tensor([[1, 1],
                    [2, 2]])

b = torch.tensor([[2, 2],
                    [3, 3]])

# Suma / resta

print(a + b)
```

**Formas incompatibles**

```{python}
#| eval: false
a = torch.tensor([[1, 1],
                    [2, 2]])

b = torch.tensor([[2, 2, 4],
                  [3, 3, 5]])

# Suma / resta

print(a + b)
```

- Multiplicación por elementos

```{python}
a = torch.tensor([[1, 1],
                  [2, 2]])

b = torch.tensor([[2, 2],
                  [3, 3]])

print(a* b)
```

- Multiplicación de matrices

```{python}
a = torch.tensor([[1, 1],
                  [2, 2]])

b = torch.tensor([[2, 2],
                  [3, 3]])

print(a @ b)
```

### Introducción a los tensores de PyTorch

Los Tensores son la estructura de datos central de PyTorch y la base de aprendizaje profundo. Son similares a las matrices Numpy, pero tienen características únicas.

Aquí tienes una lista Python llamada `temperatures` que contiene lecturas diarias de dos estaciones metereológicass. ¡Intenta convertir esto en un tensor!

#### Instucciones

- Comienza importando `torch`.

- Crea un tensor a partir de la lista Python `temperatures`.

```{python}
# Import PyTorch
import torch

temperatures = [[72, 75, 78], [70, 73, 76]]

# Create a tensor from temperatures
temp_tensor = torch.tensor(temperatures)

print(temp_tensor)
```
Se ha creado con éxito un tensor usando datos de temperatura. ¡Este es tu primer paso hacia la construcción de la primear red neuronal!


### Comprobar y sumar tensores

Mientras recoges los datos de temperatura, observas que las lecturas tienen una desviación de dos grados. Añade dos grados al tensor `temperatures` después de verificar su forma y tipo de datos con `torch` para garantizar la compatabilidad con el tensor `adjustment`.

#### Instucciones

1. 
- Visualiza la forma del tensor `adjustment`.

- Muestra el tipo de datos del tensor `adjustment`.

```{python}
adjustment = torch.tensor([[2, 2, 2], [2, 2, 2]])

# Display the shape of the adjustment tensor
print("Adjustment shape:", adjustment.shape)

# Display the type of the adjustment tensor
print("Adjustment type:", adjustment.dtype)

print("Tempeartures shape:", temp_tensor.shape)
print("Tempeartures shape:", temp_tensor.dtype)
```

2.  
- Suma los tensores `temperatures` y `adjustment`

```{python}
# Add the temperatures and adjustment tensors
corrected_temperatures = temp_tensor + adjustment
print("Corrected temperatures:", corrected_temperatures)
```

## Redes neuronales y capas

### Red de capas lineales

### Comprender los pesos


## Capas y parámetros ocultos

### Tu perimera red neuronal

### Apilar capas lineales

### Contar el número de parámetros
