# Regresión

En este capítulo , te introducirás en la regresión y construirás modelos para predecir los valores de las ventas utilizando un conjunto de datos sobre gastos publicitarios. Aprenderás la mecánica de la regresión lineal y las métricas de rendimiento más comunes,como r_squared y error cuadrático medio. Realizarás la validación cruzada k-fold y aplicarás la regularización a los modelos de regresión para reducir el riesgo de sobreajuste.

## Introducción a la regresión

- Predicción de niveles de glucosa

```{python}
import pandas as pd
ruta = './data/Diabetes Clean Data.csv'
diabetes_df = pd.read_csv(ruta)
diabetes_df.head()
```

- Creación de matrices de características y objetivos

```{python}
X = diabetes_df.drop('glucose', axis=1).values
y = diabetes_df['glucose'].values
print(type(X), type(y))
```

- Predicciones a partir de una única característica

```{python}
X_bmi = X[:, 4]
print(y.shape, X_bmi.shape)
```

```{python}
X_bmi = X_bmi.reshape(-1, 1) # necesario para poder usarlo en scikit learn
print(X_bmi.shape)
```

- Representación gráfica de la glucosa frente al índice de masa corporal

```{python}
import matplotlib.pyplot as plt

plt.scatter(X_bmi, y)
plt.ylabel('Blood Glucose (mg/dL)')
plt.xlabel('Body Mass Index')
plt.show()
```

- Ajuste de un modelo de regresión

```{python}
from sklearn.linear_model import LinearRegression

reg = LinearRegression()
reg.fit(X_bmi, y)
predictions = reg.predict(X_bmi)

plt.scatter(X_bmi, y)
plt.plot(X_bmi, predictions)
plt.ylabel('Blood Glucose (mg/dL)')
plt.xlabel('Body Mass Index')
plt.show()
```

### Crear características

En este capítulo, trabajarás con un conjunto de datos llamado `sales_df`, que contine información sobre el gasto en camapañas publicitarias en distintos tipos de medios y el número de dólares generados en ventas por la campaña respectiva. Aquí tienes las dos primeras filas:

```{python}
#| echo: false
#| eval: true
ruta = './data/sales_df.csv'
sales_df = pd.read_csv(ruta)
sales_df.head(2)
```

Utilizarás los gastos de publicidad como características para predecir los valores de las ventas, trabajando inicialmente con la columna `"radio"`. Sin embargo, antes de hacer ninguna predicción, tendrás que crear la matriz de características y objetivos, dándoles el formato correcto para scikit-learn.

#### Instrucciones

- Crea `X`, una matriz con los valores de la columna `"radio"` del DataFrame `sales_df`.

- Crea `y`, una matriz con los valores de la columna `"sales"` del DataFrame `sales_df`.

- Remodela `X` en una matriz Numpy bidimensional.

- Imprime la forma de `X` y `y`.

```{python}
import numpy as np

# Create X from de radio column's values
X = sales_df['radio'].values

# Create y from de sales column's values
y = sales_df['sales'].values

# Reshape X
X = X.reshape(-1, 1)

# Check the shape of the features and targets
print(X.shape, y.shape)
```

### Construye un modelo de regresión lineal

Ahora que has creado tus matrices de características  y objetivos, entrenaras un modelo de regresión lineal en todos los valores de características y objetivos.

Como el objetivo es evaluar la relación entre la característica y los valores objetivo, no es necesario dividir los datos en conjuntos de entrenamiento y prueba.

`X` y `y` se han precargado de la siguiente manera

```{python}
y = sales_df['sales'].values
X = sales_df['radio'].values.reshape(-1, 1) 
```

#### Instrucciones

- Importa `LinearRegression`.

- Instancia un modelo de regresión lineal.

- Predice los valores de venta utilizando `X`, almacenando como `predictions`.

```{python}
# Import LinearRegression
from sklearn.linear_model import LinearRegression

# Create the model
reg = LinearRegression()

# Fit the model to the data
reg.fit(X, y)

# Make predictions
predictions = reg.predict(X)

print(predictions[:5])
```

Se observa cómo los valores de la ventas para las primeras cinco predcciones varían de $95.000 a mas de $290.000.

### Visualizar un modelo de regresión lineal

Ahora que has construído el modelo de regresión lineal y lo has entrenado utilizando todas las observaciones disponibles, puedes visualizar lo bien que se ajusta el modelo a los datos. Esto te permite interpretar la relación entre el gasto en publicidad de `radio` y los valores de `sales`.

#### Instrucciones

- Importa `matplotlib.pyplot` como `plt`.

- Crea un gráfico de dispersión visualizando `y` frente a `X`, con las observaciones en azul.

- Visualiza el gráfico.

```{python}
# Import matplotlib.pyplot
import matplotlib.pyplot as plt

# Create a scatter plot
plt.scatter(X, y, color='blue')

# Create line plot
plt.plot(X, predictions, color='red')
plt.xlabel('Radio Expenditure ($)')
plt.ylabel('Sales ($)')

# Display the plot
plt.show()
```
¡El modelo captura muy bien una correlación lineal casi perfecta entre el gasto en publicidad en radio y las ventas! 





